# Generated by Django 5.2.14 on 2026-05-08 13:36

from django.db import migrations, models
from django.conf import settings


def delete_null_user_images(apps, schema_editor):
    """Delete UploadedImage records with null user."""
    UploadedImage = apps.get_model("retina_app", "UploadedImage")
    UploadedImage.objects.filter(user__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('retina_app', '0003_predictionrecord'),
    ]

    operations = [
        # Step 1: Handle existing null user records
        migrations.RunPython(
            delete_null_user_images,
            migrations.RunPython.noop
        ),
        # Step 2: Make user field non-nullable
        migrations.AlterField(
            model_name='uploadedimage',
            name='user',
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL
            ),
        ),
        # Step 3: Add indexes to UploadedImage
        migrations.AddIndex(
            model_name='uploadedimage',
            index=models.Index(fields=['user', '-uploaded_at'], name='retina_app_upload_user_time_idx'),
        ),
        # Step 4: Add is_deleted field and indexes to PredictionRecord
        migrations.AddField(
            model_name='predictionrecord',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='predictionrecord',
            index=models.Index(fields=['user', '-created_at'], name='retina_app_pred_user_time_idx'),
        ),
        migrations.AddIndex(
            model_name='predictionrecord',
            index=models.Index(fields=['predicted_class'], name='retina_app_pred_class_idx'),
        ),
    ]
