# Generated by Django 5.2.14 on 2026-05-09 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retina_app", "0006_add_patient_and_clinical_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("organization", models.CharField(blank=True, max_length=100)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("doctor", "Ophthalmologist / Doctor"),
                            ("technician", "Medical Technician"),
                            ("researcher", "Researcher"),
                            ("student", "Medical Student"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="profile", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
