# Generated by Django 5.2.14 on 2026-07-07 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retina_app", "0007_userprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.RemoveIndex(
            model_name="predictionrecord",
            name="retina_app__user_id_cb59d8_idx",
        ),
        migrations.RemoveIndex(
            model_name="uploadedimage",
            name="retina_app__user_id_d667c0_idx",
        ),
        migrations.AlterField(
            model_name="predictionrecord",
            name="clinical_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="predictionrecord",
            name="model_version",
            field=models.CharField(default="ensemble-v3", max_length=128),
        ),
        migrations.AlterField(
            model_name="predictionrecord",
            name="patient_identifier",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="predictionrecord",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="predictions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="uploadedimage",
            name="user",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="predictionrecord",
            index=models.Index(fields=["-created_at"], name="retina_app__created_2877a6_idx"),
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
